In [7]:
#Exercício 1

valor_emprestimo = float(input('Insira o valor do empréstimo'))
salario = float(input('Insira o seu salário'))
anos = int(input('Número de anos do financiamento'))

prestacaoMensal = valor_emprestimo / (12 * anos)

if prestacaoMensal > salario * 0.3 :
    print(f'O Crédito não foi aprovado')
else:
    print(f'Empréstimo Aprovado')
    print(f'A prestação mensal vai ser de {prestacaoMensal} euros, durante {anos} anos')


Insira o valor do empréstimo 1500000
Insira o seu salário 1050
Número de anos do financiamento 40


O Crédito não foi aprovado


In [1]:
# Exercício 4
lista = []

valor = float(input("Insira um valor numérico: "))

while valor >= 0:
    
    if valor not in lista:
        lista.append(valor)
        
    valor = float(input("Insira um valor numérico: "))
    
quantidade = len(lista)

if quantidade > 0:
    maior = lista[0]
    menor = lista[0]
    pos_maior = 0
    pos_menor = 0
    
    for i in range(len(lista)):
        if lista[i] > maior:
            maior = lista[i]
            pos_maior = i
        
        if lista[i] < menor:
            menor = lista[i]
            pos_menor = i

    print(f"Número de elementos não repetidos: {quantidade}")
    print(f"Maior número: {maior} Posição: {pos_maior}")
    print(f"Menor número: {menor} Posição: {pos_menor}")
else:
    print("Nenhum número válido foi inserido.")


Insira um valor numérico:  10
Insira um valor numérico:  30
Insira um valor numérico:  45
Insira um valor numérico:  89934
Insira um valor numérico:  10
Insira um valor numérico:  3
Insira um valor numérico:  2
Insira um valor numérico:  1
Insira um valor numérico:  0
Insira um valor numérico:  -3


Número de elementos não repetidos: 8
Maior número: 89934.0 Posição: 3
Menor número: 0.0 Posição: 7


In [14]:
#Exercício 5
lista = []
indice = 0
for i in range(5):
    valor = float(input('Insira um valor númerico: '))
    while indice < len(lista) and valor > lista[indice]:
        indice+=1
    lista.insert(indice, valor)
print("Lista Ordenada: ", lista)

Insira um valor númerico:  10
Insira um valor númerico:  9
Insira um valor númerico:  8
Insira um valor númerico:  7
Insira um valor númerico:  6


Lista Ordenada:  [6.0, 7.0, 8.0, 9.0, 10.0]


In [6]:
#Exercício 7 
import numpy as np
n = int(input('Insira o valor n Matrix: (n x n): '));
matriz = np.zeros((n, n), dtype=int)  # note os parênteses (n, n)


for i in range(n):
    for j in range(n):
        matriz[i][j] = int(input(f'Insira o valor da posição "[{i}][{j}]: '))

print("\nMatriz:")
print(matriz)

soma_pares = np.sum(matriz[matriz % 2 == 0])
print (f'Soma dos valores pares: {soma_pares}')

if n >=3:
    soma_terceira_coluna = np.sum(matriz[: ,2])
    print(f'Soma da terceira coluna: {soma_terceira_coluna}')
else:
    print('A matriz não tem terceira coluna')
if n>=2:
    print(f'O menor valor da segunda linha é: {np.min(matriz[1])}')
else:
    print('A matriz não tem segunda coluna')

Insira o valor n Matrix: (n x n):  5
Insira o valor da posição "[0][0]:  1
Insira o valor da posição "[0][1]:  2
Insira o valor da posição "[0][2]:  3
Insira o valor da posição "[0][3]:  4
Insira o valor da posição "[0][4]:  5
Insira o valor da posição "[1][0]:  1
Insira o valor da posição "[1][1]:  2
Insira o valor da posição "[1][2]:  3
Insira o valor da posição "[1][3]:  4
Insira o valor da posição "[1][4]:  5
Insira o valor da posição "[2][0]:  1
Insira o valor da posição "[2][1]:  2
Insira o valor da posição "[2][2]:  3
Insira o valor da posição "[2][3]:  4
Insira o valor da posição "[2][4]:  5
Insira o valor da posição "[3][0]:  1
Insira o valor da posição "[3][1]:  2
Insira o valor da posição "[3][2]:  3
Insira o valor da posição "[3][3]:  4
Insira o valor da posição "[3][4]:  5
Insira o valor da posição "[4][0]:  1
Insira o valor da posição "[4][1]:  2
Insira o valor da posição "[4][2]:  3
Insira o valor da posição "[4][3]:  4
Insira o valor da posição "[4][4]:  5



Matriz:
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
Soma dos valores pares: 30
Soma da terceira coluna: 15
O menor valor da segunda linha é: 1


In [16]:
#Exercício 10
import numpy as np
def maior(variosValoresInteiros):
    print (f'O maior número inteiro é {np.max(variosValoresInteiros)}')

valores = [];

input_inteiro = int(input('Insira um valor inteiro: '))
valores.append(input_inteiro)

while input_inteiro > 0:
    input_inteiro = int(input('Insira um valor inteiro: '))
    valores.append(input_inteiro)

maior(valores)

Insira um valor inteiro:  39384838438483
Insira um valor inteiro:  493984389483843848384
Insira um valor inteiro:  9999999
Insira um valor inteiro:  33
Insira um valor inteiro:  4
Insira um valor inteiro:  5
Insira um valor inteiro:  34
Insira um valor inteiro:  3
Insira um valor inteiro:  5
Insira um valor inteiro:  -6


O maior número inteiro é 493984389483843848384
